Metrics/LineLength:
  Max: 100

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Documentation:
  Enabled: false

AllCops:
  Exclude:
    - 'config/**/*'
    - 'bin/**/*'
